BlogCore/Areas/Admin/Controllers/CategoriasController.cs
using BlogCore.AccesoDatos.Data.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using BlogCore.Data;
using BlogCore.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using BlogCore.Utilidades;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize(Roles = ConstantsAuth.AdminRole)]
    [Area("Admin")]
    public class CategoriasController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        public CategoriasController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        #region llamadas a la vista
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new Categoria());
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var categoria = _contenedorTrabajo.Categoria.Get(id.GetValueOrDefault());
            if (categoria == null)
                return NotFound();

            return View(categoria);
        }

        #endregion

        #region llamadas al controlador
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                var objDesdeDb = _contenedorTrabajo.Categoria.ExisteCategoria(categoria.Nombre);
                if (objDesdeDb != null)
                {
                    ModelState.AddModelError("", "La categoría ya existe");
                    return View(categoria);
                }
                var objDesdeDb2 = _contenedorTrabajo.Categoria.ExisteCategoriaOrden(categoria.Orden);
                if (objDesdeDb2 != null)
                {
                    ModelState.AddModelError("", "El orden ya existe");
                    return View(categoria);
                }
                _contenedorTrabajo.Categoria.Add(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                var objDesdeDb = _contenedorTrabajo.Categoria.ExisteCategoriaSinEllaMisma(categoria.Nombre, categoria.Id);
                if (objDesdeDb != null)
                {
                    ModelState.AddModelError("", "La categoría ya existe");
                    return View(categoria);
                }
                var objDesdeDb2 = _contenedorTrabajo.Categoria.ExisteCategoriaOrdenSinEllaMisma(categoria.Orden, categoria.Id);
                if (objDesdeDb2 != null)
                {
                    ModelState.AddModelError("", "El orden ya existe");
                    return View(categoria);
                }
                _contenedorTrabajo.Categoria.Update(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }
        #endregion

        #region llamadas a la api
        // [AllowAnonymous] // para permitir que se pueda acceder a la api sin estar logueado
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Categoria.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objDesdeDb = _contenedorTrabajo.Categoria.Get(id);
            if (objDesdeDb == null)
                return Json(new { success = false, message = "Error borrando categoría" });

            _contenedorTrabajo.Categoria.Remove(objDesdeDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Categoría borrada correctamente" });
        }
        #endregion

        #region Lllamada de error
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        #endregion
    }
}

BlogCore/Areas/Admin/Controllers/SlidersController.cs
using System.Diagnostics;
using BlogCore.AccesoDatos.Data.Repository.IRepository;
using BlogCore.Data;
using BlogCore.Models;
using BlogCore.Models.ViewModels;
using BlogCore.Utilidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize(Roles = ConstantsAuth.AdminRole)]
    [Area("Admin")]
    public class SlidersController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly IWebHostEnvironment _hostEnvironment;
        public SlidersController(IContenedorTrabajo contenedorTrabajo, IWebHostEnvironment hostEnvironment)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _hostEnvironment = hostEnvironment;
        }

        #region llamadas a la vista
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new Slider());
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id != null && id != 0)
            {
                var slider = _contenedorTrabajo.Slider.Get(id.GetValueOrDefault());
                if (slider == null)
                    return NotFound();
                return View(slider);
            }
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region llamadas al controlador
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Slider slider)
        {
            if (ModelState.IsValid)
            {
                var objDesdeDb = _contenedorTrabajo.Slider.ExisteSlider(slider.Nombre);
                if (objDesdeDb != null)
                {
                    ModelState.AddModelError("", "El slider ya existe");
                    return View(slider);
                }

                string rutaPrincipal = _hostEnvironment.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;

                if (archivos.Count > 0) // Hay imagen
                {
                    if (slider.Id == 0)
                    {
                        // Nuevo slider
                        string nombreArchivo = Guid.NewGuid().ToString();
                        var subidas = Path.Combine(rutaPrincipal, @"imagenes\sliders");
                        var extension = Path.GetExtension(archivos[0].FileName);

                        using (var fileStreams = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                        {
                            archivos[0].CopyTo(fileStreams);
                        }
                        slider.UrlImagen = @"\imagenes\sliders\" + nombreArchivo + extension;
                    }
                }
                else
                {
                    // No hay imagen
                    slider.UrlImagen = @"\imagenes\sliders\default.png";
                }
                slider.Estado = true; // false es inactivo y true es activo
                _contenedorTrabajo.Slider.Add(slider);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(slider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Slider slider)
        {
            if (ModelState.IsValid)
            {
                var objDesdeDb = _contenedorTrabajo.Slider.ExisteSliderSinEllaMisma(slider.Nombre, slider.Id);
                if (objDesdeDb != null)
                {
                    ModelState.AddModelError("", "Ya existe un slider con ese nombre");
                    return View(slider);
                }

                string rutaPrincipal = _hostEnvironment.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;
                var sliderDesdeDb = _contenedorTrabajo.Slider.Get(slider.Id);

                if (archivos.Count > 0) // Hay imagen
                {
                    // Nuevo slider
                    string nombreArchivo = Guid.NewGuid().ToString();
                    var subidas = Path.Combine(rutaPrincipal, @"imagenes\sliders");
                    var extension = Path.GetExtension(archivos[0].FileName);
                    if (sliderDesdeDb.UrlImagen != @"\imagenes\sliders\default.png") // Si no es la imagen por defecto
                    {
                        // Borrar imagen anterior
                        var nuevaRutaImagen = Path.Combine(rutaPrincipal, sliderDesdeDb.UrlImagen.TrimStart('\\'));
                        if (System.IO.File.Exists(nuevaRutaImagen))
                            System.IO.File.Delete(nuevaRutaImagen);
                        // Subir nueva imagen
                        using (var fileStreams = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                        {
                            archivos[0].CopyTo(fileStreams);
                        }
                        slider.UrlImagen = @"\imagenes\sliders\" + nombreArchivo + extension;
                    }
                    else
                    {
                        // Subir nueva imagen
                        using (var fileStreams = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                        {
                            archivos[0].CopyTo(fileStreams);
                        }
                        slider.UrlImagen = @"\imagenes\sliders\" + nombreArchivo + extension;
                    }
                }
                else
                {
                    // No hay imagen
                    slider.UrlImagen = sliderDesdeDb.UrlImagen;
                }

                slider.Estado = sliderDesdeDb.Estado;
                _contenedorTrabajo.Slider.Update(slider);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(slider);
        }
        #endregion

        #region llamadas a la api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Slider.GetAll() });
        }

        [HttpPost]
        public IActionResult CambiarEstado(int id)
        {
            var sliderDesdeDb = _contenedorTrabajo.Slider.Get(id);
            if (sliderDesdeDb == null)
                return Json(new { success = false, message = "Error cambiando el estado del slider" });

            sliderDesdeDb.Estado = !sliderDesdeDb.Estado;

            _contenedorTrabajo.Slider.Update(sliderDesdeDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Estado cambiado correctamente" });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var sliderDesdeDb = _contenedorTrabajo.Slider.Get(id);
            if (sliderDesdeDb == null)
                return Json(new { success = false, message = "Error borrando slider" });

            string rutaPrincipal = _hostEnvironment.WebRootPath;
            if (sliderDesdeDb.UrlImagen != @"\imagenes\sliders\default.png") // Si no es la imagen por defecto
            {
                // Borrar imagen anterior
                var nuevaRutaImagen = Path.Combine(rutaPrincipal, sliderDesdeDb.UrlImagen.TrimStart('\\'));
                if (System.IO.File.Exists(nuevaRutaImagen))
                    System.IO.File.Delete(nuevaRutaImagen);

                _contenedorTrabajo.Slider.Remove(sliderDesdeDb);
                _contenedorTrabajo.Save();
                return Json(new { success = true, message = "Slider borrado correctamente" });
            }
            else
            {
                _contenedorTrabajo.Slider.Remove(sliderDesdeDb);
                _contenedorTrabajo.Save();
                return Json(new { success = true, message = "Slider borrado correctamente" });
            }
        }
        #endregion

        #region Llamada de error
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        #endregion
    }
}

BlogCore/Areas/Admin/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BlogCore.AccesoDatos.Data.Repository.IRepository;
using BlogCore.Models;
using BlogCore.Models.ViewModels;
using BlogCore.Utilidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize(Roles = ConstantsAuth.AdminRole)]
    [Area("Admin")]
    public class UsuariosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        public UsuariosController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        // GET
        [HttpGet]
        public IActionResult Index()
        {
            // obtener todos los usuarios
            return View(
                _contenedorTrabajo.Usuario.GetAll()
            );

            // obtener todos los usuarios menos el actual
            //var claimsIdentity = (ClaimsIdentity)User.Identity;
            //var usuarioActual = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            //return View(
            //    _contenedorTrabajo.Usuario.GetAll(u => u.Id != usuarioActual.Value)
            //);
        }

        // GET - Bloquear
        // [HttpGet]
        // // [ActionName("Bloquear")]
        // public IActionResult Bloquear(string id)
        // {
        //     if (id == null || id.Trim().Length == 0)
        //     {
        //         return NotFound();
        //     }

        //     _contenedorTrabajo.Usuario.BloquearUsuario(id);
        //     return RedirectToAction(nameof(Index));
        // }

        // // GET - Desbloquear
        // [HttpGet]
        // // [ActionName("Desbloquear")]
        // public IActionResult Desbloquear(string id)
        // {
        //     if (id == null || id.Trim().Length == 0)
        //     {
        //         return NotFound();
        //     }

        //     _contenedorTrabajo.Usuario.DesbloquearUsuario(id);
        //     return RedirectToAction(nameof(Index));
        // }

        #region Api llamadas
        // GET - Api - Obtener todos los usuarios
        [HttpGet]
        public IActionResult GetUsuarios()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var usuarioActual = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return Json(new
            {
                data = _contenedorTrabajo.Usuario.GetUsuariosRoles(u => u.Id != usuarioActual.Value)
            });
        }
        // POST - Api - Bloquear usuario
        [HttpPost]
        public IActionResult Bloquear(string id)
        {
            if (id == null || id.Trim().Length == 0)
            {
                return NotFound();
            }

            _contenedorTrabajo.Usuario.BloquearUsuario(id);
            return Json(new { success = true, message = "Operación exitosa." });
        }
        // POST - Api - Desbloquear usuario
        [HttpPost]
        public IActionResult Desbloquear(string id)
        {
            if (id == null || id.Trim().Length == 0)
            {
                return NotFound();
            }

            _contenedorTrabajo.Usuario.DesbloquearUsuario(id);
            return Json(new { success = true, message = "Operación exitosa." });
        }
        #endregion

        #region Llamada de error
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        #endregion
    }
}

BlogCore/Views/Shared/_Layout.cshtml
@using BlogCore.Helpers
@using BlogCore.Utilidades
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/BlogCore.styles.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Cliente" asp-controller="Home" asp-action="Index">BlogCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    @if (User.IsInRole(ConstantsAuth.AdminRole))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Contenidos
                                </a>
                                <ul class="dropdown-menu bg-white" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Categorias" asp-action="Index">Categorías</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Articulos" asp-action="Index">Artículos</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Sliders</a></li>
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Usuarios" asp-action="Index">Usuarios</a></li>
                                </ul>
                            </li>
                        </ul>
                    }
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - BlogCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/0f48d8c00d.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogCore/Views/Shared/_VistaCrearVolver.cshtml
<div class="col-12">
    <a asp-action="Index" class="btn btn-secondary float-end">Cancelar</a>
    <button type="submit" class="btn btn-primary float-end me-2">Crear</button>
</div>